### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by mackeyja92** [darayus/iron-diesel-middleware#1]
Could you provide some example usage?

**Comment by darayus** [comment]
I've added a basic example in the examples folder and uploaded a copy of the documentation [here](https://docs.darayus.com/iron_diesel_middleware/iron_diesel_middleware/). You can try out the example locally by running `cargo run --example basic` and visiting http://127.0.0.1:8000.

**Comment by mackeyja92** [comment]
Looks sweet, I will test it out shortly. Thanks a bunch!
